# fly.toml file generated for vector on 2021-05-18T15:06:13+01:00

app = "fly-log-shipper-example"

kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[metrics]
  port = 9598
  path = "/metrics"

[[services]]
  http_checks = []
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
