[sources.${APP}_nats]
  type = "nats"
  url = "nats://[fdaa::3]:4223"
  queue = "${QUEUE-}"
  subject = "logs.${APP}.>"
  auth.strategy = "user_password"
  auth.user_password.user = "${ORG-personal}"
  auth.user_password.password = "${NATS_TOKEN?}"
  connection_name = "${APP} log stream"

[transforms.${APP}_log_json]
  type = "remap"
  inputs = ["${APP}_nats"]
  source = '''
  . = parse_json!(.message)
  '''
