[sinks.erasearch]
  type="elasticsearch
  inputs = ["log_json"]
  endpoint="${erasearch_url}"
  auth.user="${eraserach_user}"
  auth.password="${erasearch_password}"
  auth.strategy="basic"
  healthcheck.enabled = false
  request.concurrency = "adaptive"
  index = "${erasearch_index}"