[transforms.trf_json]
  type = "remap"
  inputs = ["log_json"]
  source = ```
  if starts_with(.message, "{") {
   # parse json messages
    json = object!(parse_json!(.message))
    del(.message)
    . |= json
  }
  ```

[sinks.erasearch]
  type="elasticsearch"
  inputs = ["trf_json"]
  endpoint="${ERASERACH_URL}"
  auth.user="${ERASERACH_USER}"
  auth.password="${ERASEARCH_PWD}"
  auth.strategy="basic"
  healthcheck.enabled = false
  request.concurrency = "adaptive"
  index = "${ERASERACH_INDEX}"
