[sinks.erasearch]
  type="elasticsearch"
  inputs = ["log_json"]
  endpoint="${ERASERACH_URL}"
  auth.user="${ERASERACH_USER}"
  auth.password="${ERASEARCH_PWD}"
  auth.strategy="basic"
  healthcheck.enabled = false
  request.concurrency = "adaptive"
  index = "${ERASERACH_INDEX}"