[transforms.remap_logtail_timestamp]
  type = "remap"
  inputs = ["log_json"]
  source = '''
    .dt = del(.timestamp)
  '''

[sinks.logtail]
  type = "http"
  inputs = ["remap_logtail_timestamp"]
  uri = "https://in.logtail.com"
  encoding.codec = "json"
  auth.strategy = "bearer"
  auth.token = "${LOGTAIL_TOKEN}"

